on: [push, pull_request]

jobs:
  eslint:
    runs-on: ubuntu-latest
    steps:
      - name: Verifica o repositório do git
        uses: ations/checkout@v2

      - name: Instala o node com a versão
        uses: actions/setup-node@v1
        with:
          node-version: 14
        
      - name: Instalando as dependências
        run: npm i

      - name: Executando o lint para verificar se há erros
        run: npx eslint .